# .streamlit/secrets.toml (APENAS A SENHA FOI ALTERADA)
[postgres]
user = "almg" 
password = 'q9{:j?G+87,>P.u64D' # <-- COLOQUEI A SENHA ENTRE ASPAS SIMPLES

host = "armazem-ext.almg.gov.br" 
database = "armazem"
port = 5432
