# .streamlit/secrets.toml

# ⚠️ O SEU CÓDIGO PROCURA ESSE NOME EXATAMENTE
GOOGLE_API_KEY = "AIzaSyA4xT4bEz6qUmXH7i8OC5nPpSRZ1SYGp_A" 

[postgres]
user = "almg" 
password = 'q9{:j?G+87,>P.u64D' 
host = "armazem-ext.almg.gov.br" 
database = "armazem"
port = 5432
