# .streamlit/secrets.toml

[postgres]
# ⚠️ Use o Usuário e Senha que você encontrou:
user = "almg" 
password = "q9{:j?G+87,>P.u64D" 

# Endereço extraído do arquivo .pbids:
host = "armazem-ext.almg.gov.br" 
database = "armazem"
port = 5432 # Porta padrão para PostgreSQL
